"""create knowledge base schema

Revision ID: 11160c9078cc
Revises: 0001
Create Date: 2026-08-02 15:44:34.394562
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = '11160c9078cc'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_service_account', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attribute',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value_type', sa.String(length=64), server_default='string', nullable=False),
    sa.Column('multivalue', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("value_type IN ('string', 'number', 'boolean', 'date', 'json')", name='ck_attribute_value_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'name', name='uq_attribute_namespace_name')
    )
    op.create_table('entity',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'name', name='uq_entity_type_name')
    )
    op.create_table('knowledge_category',
    sa.Column('category_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['knowledge_category.category_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('knowledge_source',
    sa.Column('source_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('FILE_UPLOAD', 'EXTERNAL_INTEGRATION', name='knowledge_source_type'), nullable=False),
    sa.Column('origin_system', sa.Text(), nullable=True),
    sa.Column('external_reference_id', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_category.category_id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['knowledge_source_version.version_id'], name='fk_knowledge_source_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('relation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relation_source_entity_id'), 'relation', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_relation_target_entity_id'), 'relation', ['target_entity_id'], unique=False)
    op.create_table('value',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('searchable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_attribute_id'), 'value', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_value_entity_id'), 'value', ['entity_id'], unique=False)
    op.create_table('knowledge_source_version',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'MD', name='knowledge_file_type'), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'FAILED', 'STALE', 'ARCHIVED', name='knowledge_version_status'), server_default='PENDING', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('last_reindexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_source.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('checksum'),
    sa.UniqueConstraint('source_id', 'version_number', name='uq_knowledge_source_version_source_version')
    )
    op.create_index(op.f('ix_knowledge_source_version_source_id'), 'knowledge_source_version', ['source_id'], unique=False)
    op.create_table('embedding_chunk',
    sa.Column('chunk_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_source_version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_embedding_chunk_checksum'), 'embedding_chunk', ['checksum'], unique=False)
    op.create_index(op.f('ix_embedding_chunk_entity_id'), 'embedding_chunk', ['entity_id'], unique=False)
    op.create_index(op.f('ix_embedding_chunk_version_id'), 'embedding_chunk', ['version_id'], unique=False)
    op.create_table('knowledge_injection_job',
    sa.Column('job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Enum('INITIAL_INGEST', 'REINDEX', 'UPDATE', 'DELETE', name='knowledge_job_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='knowledge_job_status'), server_default='QUEUED', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Text(), nullable=False),
    sa.Column('chunks_created_count', sa.Integer(), nullable=True),
    sa.Column('entities_created_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_source.source_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_source_version.version_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_knowledge_injection_job_source_id'), 'knowledge_injection_job', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_injection_job_version_id'), 'knowledge_injection_job', ['version_id'], unique=False)
    op.create_table('knowledge_source_entity_map',
    sa.Column('map_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PRIMARY_DOCUMENT', 'DERIVED_SECTION', 'DERIVED_CHUNK', 'SUPPLEMENTARY', name='knowledge_relationship_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_source_version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id')
    )
    op.create_index(op.f('ix_knowledge_source_entity_map_entity_id'), 'knowledge_source_entity_map', ['entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_source_entity_map_version_id'), 'knowledge_source_entity_map', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_source_entity_map_version_id'), table_name='knowledge_source_entity_map')
    op.drop_index(op.f('ix_knowledge_source_entity_map_entity_id'), table_name='knowledge_source_entity_map')
    op.drop_table('knowledge_source_entity_map')
    op.drop_index(op.f('ix_knowledge_injection_job_version_id'), table_name='knowledge_injection_job')
    op.drop_index(op.f('ix_knowledge_injection_job_source_id'), table_name='knowledge_injection_job')
    op.drop_table('knowledge_injection_job')
    op.drop_index(op.f('ix_embedding_chunk_version_id'), table_name='embedding_chunk')
    op.drop_index(op.f('ix_embedding_chunk_entity_id'), table_name='embedding_chunk')
    op.drop_index(op.f('ix_embedding_chunk_checksum'), table_name='embedding_chunk')
    op.drop_table('embedding_chunk')
    op.drop_index(op.f('ix_knowledge_source_version_source_id'), table_name='knowledge_source_version')
    op.drop_table('knowledge_source_version')
    op.drop_index(op.f('ix_value_entity_id'), table_name='value')
    op.drop_index(op.f('ix_value_attribute_id'), table_name='value')
    op.drop_table('value')
    op.drop_index(op.f('ix_relation_target_entity_id'), table_name='relation')
    op.drop_index(op.f('ix_relation_source_entity_id'), table_name='relation')
    op.drop_table('relation')
    op.drop_table('knowledge_source')
    op.drop_table('knowledge_category')
    op.drop_table('entity')
    op.drop_table('attribute')
    op.drop_table('app_user')
    # ### end Alembic commands ###
