"""The Postgres I/O boundary for the storage layer.

Just as ``client.py`` is the only module that talks to the MinIO SDK,
``repository.py`` is the only module in ``storage/`` that talks to the
database. ``uploader.py`` composes the two at its edges and otherwise
stays pure. Every function here does exactly one statement's worth of
work and returns immutable data — no ORM instances leak out of this
module for callers to mutate.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Literal
from uuid import UUID, uuid4

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from .models import KnowledgeInjectionJob, KnowledgeSource, KnowledgeSourceVersion

JobType = Literal["INITIAL_INGEST", "REINDEX", "UPDATE", "DELETE"]


@dataclass(frozen=True, slots=True)
class ExistingVersionRef:
    """A prior version whose checksum already matches — the dedup hit."""

    source_id: UUID
    version_id: UUID
    version_number: int
    status: str


@dataclass(frozen=True, slots=True)
class NewVersionRef:
    """A freshly inserted, still-``PENDING`` version row."""

    source_id: UUID
    version_id: UUID
    version_number: int


@dataclass(frozen=True, slots=True)
class NewSourceMetadata:
    """Everything needed to create (or resolve) the parent
    ``knowledge_source`` row for a new version."""

    source_name: str
    source_type: Literal["FILE_UPLOAD", "EXTERNAL_INTEGRATION"]
    origin_system: str | None
    external_reference_id: str | None
    uploaded_by: UUID | None
    category_id: UUID | None = None


async def find_version_by_checksum(
    session: AsyncSession, checksum: str
) -> ExistingVersionRef | None:
    """Global checksum lookup — step 1 of workflow_of_ingestion.md, scoped
    across every source, not just one document."""
    stmt = select(KnowledgeSourceVersion).where(
        KnowledgeSourceVersion.checksum == checksum
    )
    row = (await session.execute(stmt)).scalar_one_or_none()
    return (
        None
        if row is None
        else ExistingVersionRef(
            source_id=row.source_id,
            version_id=row.version_id,
            version_number=row.version_number,
            status=row.status,
        )
    )


async def find_source_by_external_reference(
    session: AsyncSession, origin_system: str, external_reference_id: str
) -> UUID | None:
    """Used by the crawler flow to resolve an existing logical document by
    URL before deciding whether to create a new ``knowledge_source``."""
    stmt = select(KnowledgeSource.source_id).where(
        KnowledgeSource.origin_system == origin_system,
        KnowledgeSource.external_reference_id == external_reference_id,
    )
    return (await session.execute(stmt)).scalar_one_or_none()


async def next_version_number(session: AsyncSession, source_id: UUID) -> int:
    stmt = select(func.coalesce(func.max(KnowledgeSourceVersion.version_number), 0)).where(
        KnowledgeSourceVersion.source_id == source_id
    )
    current_max = (await session.execute(stmt)).scalar_one()
    return current_max + 1


async def get_or_create_source(
    session: AsyncSession, existing_source_id: UUID | None, metadata: NewSourceMetadata
) -> UUID:
    if existing_source_id is not None:
        return existing_source_id

    source = KnowledgeSource(
        source_id=uuid4(),
        source_name=metadata.source_name,
        source_type=metadata.source_type,
        origin_system=metadata.origin_system,
        external_reference_id=metadata.external_reference_id,
        uploaded_by=metadata.uploaded_by,
        category_id=metadata.category_id,
        current_version_id=None,
        is_active=True,
    )
    session.add(source)
    await session.flush()
    return source.source_id


async def insert_pending_version(
    session: AsyncSession,
    *,
    version_id: UUID,
    source_id: UUID,
    version_number: int,
    checksum: str,
    file_type: str | None,
    mime_type: str,
    file_size_bytes: int,
    storage_uri: str,
    metadata: dict | None = None,
) -> NewVersionRef:
    """Insert the version row with ``storage_uri`` already populated (see
    Phase 1 open question #1 — the key is deterministic from
    ``(source_id, version_id)`` and computable before the MinIO PUT, so we
    write it up front rather than risk an orphaned row if a later update
    step fails). ``version_id`` is generated by the caller (``uploader.py``)
    *before* this call, since the key must be built from it."""
    version = KnowledgeSourceVersion(
        version_id=version_id,
        source_id=source_id,
        version_number=version_number,
        file_type=file_type,
        storage_uri=storage_uri,
        checksum=checksum,
        mime_type=mime_type,
        file_size_bytes=file_size_bytes,
        status="PENDING",
        metadata_=metadata or {},
    )
    session.add(version)
    await session.flush()
    return NewVersionRef(
        source_id=source_id, version_id=version.version_id, version_number=version_number
    )


async def mark_version_failed(
    session: AsyncSession, version_id: UUID, error_details: str
) -> None:
    version = await session.get(KnowledgeSourceVersion, version_id)
    version.status = "FAILED"
    version.metadata_ = {**version.metadata_, "error_details": error_details}


async def mark_version_ingested(session: AsyncSession, version_id: UUID) -> None:
    version = await session.get(KnowledgeSourceVersion, version_id)
    version.last_ingested_at = datetime.now(UTC)


async def has_non_terminal_job(session: AsyncSession, source_id: UUID) -> bool:
    """One-job-per-document guard from workflow_of_ingestion.md step 2."""
    stmt = select(KnowledgeInjectionJob.job_id).where(
        KnowledgeInjectionJob.source_id == source_id,
        KnowledgeInjectionJob.status.in_(("QUEUED", "RUNNING")),
    )
    return (await session.execute(stmt)).first() is not None


async def enqueue_ingestion_job(
    session: AsyncSession,
    *,
    source_id: UUID,
    version_id: UUID,
    job_type: JobType,
    triggered_by: str,
) -> UUID:
    job = KnowledgeInjectionJob(
        job_id=uuid4(),
        source_id=source_id,
        version_id=version_id,
        job_type=job_type,
        status="QUEUED",
        triggered_by=triggered_by,
    )
    session.add(job)
    await session.flush()
    return job.job_id
